namespace Phobos.Enums;

public enum BsgBrain
{
    ArenaFighter,
    BossBully,
    BossGluhar,
    BossBoar,
    BossPartisan,
    Knight,
    BossKojaniy,
    BossSanitar,
    BossKolontay,
    Tagilla,
    TagillaAgro,
    BossTest,

    Obdolbs,
    ExUsec,
    BigPipe,
    BirdEye,
    FollowerBully,
    FollowerGluharAssault,
    FollowerGluharProtect,
    FollowerGluharScout,
    FollowerKojaniy,
    FollowerSanitar,
    FollowerBoar,
    FollowerBoarClose1,
    FollowerBoarClose2,
    BossBoarSniper,
    FollowerKolontayAssault,
    FollowerKolontaySecurity,
    TagillaFollower,
    TagillaHelperAgro,

    Gifter,
    Killa,
    KillaAgro,
    Marksman,
    PMC,
    SectantPriest,
    SectantWarrior,
    CursAssault,
    Assault,
    PmcBear,
    PmcUsec,
    FlBoarCl,
    FlBoarSt,
    FlKlnAslt,
    KolonSec,
}
